# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.chat_pb2 as chat__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatServiceStub(object):
    """-----------------------------------------------------------------------------
    ChatService definition
    -----------------------------------------------------------------------------

    ChatService exposes a single RPC, StreamChat, which takes a ChatRequest
    and returns a stream of ChatResponse messages.  This supports token-by-token
    or full-text streaming from both local and cloud LLMs.

    The generated Python and Dart code will let us hook into this service:
    - Python: implement ChatServiceServicer.stream_chat()
    - Dart: call ChatServiceClient(streamChat) and listen to the stream
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamChat = channel.unary_stream(
                '/secugenie.proto.chat.ChatService/StreamChat',
                request_serializer=chat__pb2.ChatRequest.SerializeToString,
                response_deserializer=chat__pb2.ChatResponse.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """-----------------------------------------------------------------------------
    ChatService definition
    -----------------------------------------------------------------------------

    ChatService exposes a single RPC, StreamChat, which takes a ChatRequest
    and returns a stream of ChatResponse messages.  This supports token-by-token
    or full-text streaming from both local and cloud LLMs.

    The generated Python and Dart code will let us hook into this service:
    - Python: implement ChatServiceServicer.stream_chat()
    - Dart: call ChatServiceClient(streamChat) and listen to the stream
    """

    def StreamChat(self, request, context):
        """StreamChat streams back ChatResponse messages for a given ChatRequest.
        The server may send multiple messages (one per token) and then terminate
        with a final response containing the full_text.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamChat': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChat,
                    request_deserializer=chat__pb2.ChatRequest.FromString,
                    response_serializer=chat__pb2.ChatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'secugenie.proto.chat.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('secugenie.proto.chat.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """-----------------------------------------------------------------------------
    ChatService definition
    -----------------------------------------------------------------------------

    ChatService exposes a single RPC, StreamChat, which takes a ChatRequest
    and returns a stream of ChatResponse messages.  This supports token-by-token
    or full-text streaming from both local and cloud LLMs.

    The generated Python and Dart code will let us hook into this service:
    - Python: implement ChatServiceServicer.stream_chat()
    - Dart: call ChatServiceClient(streamChat) and listen to the stream
    """

    @staticmethod
    def StreamChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/secugenie.proto.chat.ChatService/StreamChat',
            chat__pb2.ChatRequest.SerializeToString,
            chat__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
